nav:
  - Home: index.md
  - User Manual:
      - Quick Start: manual/cluster-user/quick-start.md
      - How to use tpods: manual/cluster-user/how-to-use-tpods.md
  - Admin Manual:
      - Installation Guide: manual/cluster-admin/installation-guide.md
plugins:
  - search
site_name: OpenPAI Handbook
theme: readthedocs
use_directory_urls: false